name: AdminDemo_CI_CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports: ['5432:5432']

      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile

      - name: Run tests
        env:
          POSTGRES_USER: ${{ job.services.postgres.env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ job.services.postgres.env.POSTGRES_PASSWORD }}
          POSTGRES_DB: admin_demo_test
          REDIS_URL: redis://localhost:6379/8
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PG_USER: ${{ job.services.postgres.env.POSTGRES_USER }}
        run: |
          chmod u+x bin/rails
          bin/rails db:test:prepare
          bundle exec rspec

  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy to server
        run: |
          git pull origin master
          bundle install
          rails db:migrate
          rails assets:precompile
          pkill -f $SERVER && puma -d -p $PORT
